# Regression and model validation

After downloading the original raw dataset, and following the instructions for creating the _approach_ variables, I obtained a new dataset which comprises of 166 observations, having 7 variables for each. We have a two factor variable for _gender_ (M/F). There are then variables containing _age_, _attitude_ and _points_. The last group of variables portray the approach of each individual; _deep_, _strategic_ and _surface_ respectively. The latter variables are either integer or numeric.

Most of the individuals are female (110:56). Majority of people in the dataset is in their early twenties, female participants being on average a little younger. The _age_ variable is therefore heavily skewed to the right. Other variables do not display such dramatic shifts - they appear to reasonably follow the normal distribution. Only the _deep_ and also _points_ variables are slightly skewed to the left. Interesting is, that while males have in general higher _attitude_ score, females score better in the approach variables. The test scores were similar for both sexes though, male median being approximately 1 higher. At the same time, male IQR is higher as well (by 1.25).

There appears to be a significant correlation between _attitude_ and _points_, and between _deep_ and _surface_ learning, both of which make sense. In my first "big" regression model, I chose _attitude_, _stra_ and _surf_ as the explanatory variables, as they have the highest correlation with _points_ variable. After running the model and obtaining the summary, I discovered that only the _attitude_ variable is statistically significant at the 5% level. After I run another "small" model, where the only explanatory variable is _attitude_. Adjusted R squared of both models is 0.1927 and 0.1856 respectively - not very high. It means that only about 20% changes in the dependent variable can be explained by the variables in our model. Other important variables are most likely omitted. Concerning the _attitude_ variable, we can say that _ceteris paribus_ with increase by 1 in _attitude_, the individual is expected to receive 3.52 _points_ more. 

Now to the diagnostic plots. Obviously, we assume linearity of the model. Also We assume that the errors are normally distributed, uncorrelated and homoscedastic (constant variance).
According to the QQ plot, errors seem to reasonably follow the normality assumption. Residuals vs fitted plot also implies that the homoscedasticity assumption is fulfilled. Residuals vs leverage plot should help identify the observations which have unusually large impact. Our plot doesn´t show any observation which would stand out significantly.
